"""Auto-PR from crawl diff."""
from __future__ import annotations
from pathlib import Path
def generate_pr_description(diff_path: Path) -> str:
    text = diff_path.read_text(encoding="utf-8") if diff_path.exists() else "No diff."
    lines = text.splitlines()[:30]
    return "\n".join(["## Crawl Change Report"] + lines + ["\nAuto-generated by FullPage Capture Bot."])
